image: python:3.6.3-jessie

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
    - apt-get update --fix-missing && apt-get install -y pandoc
    - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
    - pip install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
    - pip install -r develop.txt

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - pycodestyle --max-line-length=250 lightnet/
    - pycodestyle --max-line-length=250 test/

unittest:
  stage: test
  only:
    - tags
    - master
    - develop
  script:
    - python -m pytest ./test/

doctest:
  stage: test
  only:
    - tags
    - master
    - develop
  script:
    - cd docs; make doctest; cd ..

pages:
  stage: deploy
  only:
    - tags
  script:
    - pip install IPython
    - cd docs; make html; cd ..
    - mv docs/.build/html public/
  artifacts:
    paths:
      - public
